name: okuur
description: Read Tracker
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.0
  get_storage: ^2.1.1
  get: ^4.6.5
  flutter_native_splash: ^2.3.7
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  url_launcher: ^6.1.14
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/

  fonts:
    - family: FontRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: FontBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: FontMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: FontMediumItalic
      fonts:
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
    - family: FontLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
