List<String> bookTypeList = [
  "Türünü seçiniz",
  "Roman",
  "Anı",
  "Anlatı",
  "Araştırma-İnceleme",
  "Bilim",
  "Biyografi",
  "Çizgi Roman",
  "Deneme",
  "Edebiyat",
  "Eğitim",
  "Felsefe",
  "Gençlik",
  "Gezi",
  "Hikaye",
  "Hobi",
  "İnceleme",
  "İş Ekonomi - Hukuk",
  "Kişisel Gelişim",
  "Konuşmalar",
  "Masal",
  "Mektup",
  "Mizah",
  "Öykü",
  "Polisiye",
  "Psikoloji",
  "Resimli Öykü",
  "Sağlık",
  "Sanat - Tasarım",
  "Sanat- Müzik",
  "Sinema Tarihi",
  "Söyleşi",
  "Şiir",
  "Tarih",
  "Yemek Kitapları"
];